export const languageContent = {
  he: {
    common: {
      langHe: 'עברית',
      langEn: 'English',
      switchLanguage: 'החלפת שפה',
    },
    login: {
      brandTitle: 'Limdocs',
      brandSubtitle: 'Limdocs - למידה מותאמת אישית — התחברו או צרו חשבון',
      footer: 'Limdocs — פלטפורמת למידה אדפטיבית',
      loginFormLabel: 'טופס התחברות',
      signupFormLabel: 'טופס יצירת חשבון',
      confirmFormLabel: 'אישור חשבון',
      identifierLabel: 'שם משתמש או אימייל',
      passwordLabel: 'סיסמה',
      firstNameLabel: 'שם פרטי',
      lastNameLabel: 'שם משפחה',
      emailLabel: 'אימייל',
      usernameLabel: 'שם משתמש',
      confirmCodeLabel: 'קוד אימות',
      loginButton: 'התחברות',
      signupButton: 'צור חשבון',
      confirmButton: 'אשר חשבון',
      forgotPassword: 'שכחתי סיסמה',
      createNewAccount: 'צור חשבון חדש',
      alreadyHaveAccount: 'כבר יש לך חשבון? התחבר',
      backToLogin: 'חזרה להתחברות',
      goToConfirm: 'מעבר למסך אישור חשבון',
      confirmPrompt: 'הזינו את קוד האימות שנשלח ל־',
      yourEmail: 'האימייל שלך',
      requiredIdentifier: 'יש להזין שם משתמש או אימייל.',
      requiredPassword: 'יש להזין סיסמה.',
      fillMarkedFields: 'יש למלא את השדות המסומנים באדום.',
      fixMarkedFields: 'יש לתקן את השדות המסומנים באדום.',
      signInNextStep:
        'לא ניתן להשלים כניסה. ייתכן שנדרש שלב נוסף (למשל אימות דו-שלבי).',
      signInFailed: 'התחברות נכשלה. בדקו את הפרטים או נסו שוב מאוחר יותר.',
      userNotFound: 'שם המשתמש או האימייל אינם קיימים במערכת',
      wrongPassword: 'הסיסמה שהזנת אינה נכונה. נסה שנית.',
      userNotConfirmed: 'חשבונך טרם אומת. בדוק את המייל לקוד אישור.',
      signUpCodeSent: 'נשלח קוד אימות לאימייל. הזינו אותו למטה לאישור החשבון.',
      signUpComplete: 'ההרשמה הושלמה. כעת ניתן להתחבר.',
      signUpNotComplete: 'ההרשמה לא הושלמה. נסו שוב או פנו לתמיכה.',
      signUpFailed: 'הרשמה נכשלה. בדקו את השדות ונסו שוב.',
      confirmCodeRequired: 'נא להזין את קוד האימות מהאימייל.',
      confirmSuccess: 'החשבון אושר. ניתן להתחבר.',
      confirmFailed: 'אימות נכשל. בדקו את הקוד או שלחו קוד חדש מקונסולת Cognito.',
      requirements: {
        fullName: 'חובה להזין שם מלא (לפחות 2 מילים).',
        email: 'יש להזין כתובת אימייל תקינה (למשל: name@example.com).',
        username: 'שם משתמש חייב להכיל לפחות 3 תווים, ללא רווחים.',
        password:
          'הסיסמה אינה עומדת בדרישות. עליה להכיל:\n • לפחות 8 תווים\n • אות גדולה (A-Z) ואות קטנה (a-z)\n • לפחות מספר אחד (0-9)\n • תו מיוחד (למשל: !, @, #, $)',
      },
    },
    home: {
      loading: 'טוען…',
      navLabel: 'ניווט ראשי',
      dashboard: 'דאשבורד',
      myCourses: 'הקורסים שלי',
      documents: 'מסמכים',
      analytics: 'אנליטיקה',
      settings: 'הגדרות',
      coursesLoading: 'טוען קורסים...',
      coursesError: 'טעינת הקורסים נכשלה. נסו שוב.',
      coursesEmpty: 'עדיין לא נרשמתם לקורסים.',
      untitledCourse: 'קורס ללא שם',
      profile: 'פרופיל',
      logout: 'התנתקות',
      greeting: 'ברוך שובך, {name}',
      subtext: 'מוכנים להמשיך במסע הלמידה?',
      myCoursesSubtitle: 'ניהול והמשכת מסלולי הלמידה שאוצרו עבורכם.',
      exploreCourses: 'גילוי קורסים',
      exploreCoursesSubtitle: 'עיינו בקורסים ציבוריים שפורסמו ב־Limdocs.',
      exploreCoursesLoading: 'טוען קורסים ציבוריים…',
      exploreCoursesError: 'טעינת הקורסים הציבוריים נכשלה. נסו שוב.',
      exploreCoursesEmpty: 'אין עדיין קורסים ציבוריים.',
      exploreCourseBy: 'מאת {username}',
      exploreCourseOpenAria: 'פתיחת הקורס {name}',
      filterCourses: 'סינון',
      searchCoursesPlaceholder: 'חיפוש קורסים…',
      notificationsAria: 'התראות',
      profilePhotoAria: 'פרופיל משתמש',
      createCourseCardHint: 'העלו סילבוס או חומרים כדי ש־Limdocs יבנה עבורכם תוכנית.',
      courseMetaDocs: '{count} מסמכים',
      courseMetaDocsLoading: '… מסמכים',
      courseMetaActivity: 'עודכן {time}',
      courseMetaUnknown: '—',
      courseCardMetaLoadingAria: 'טוען נתוני קורס',
      progressLabel: 'שליטה בחומר',
      creatingCourse: 'יוצר קורס…',
      createCourse: 'יצירת קורס חדש',
      createCourseModalTitle: 'יצירת קורס חדש',
      createCourseModalSubtitle: 'הזינו את פרטי הקורס כדי להמשיך.',
      courseNameLabel: 'שם הקורס',
      courseNamePlaceholder: 'למשל: מבוא למדעי המחשב',
      courseDescriptionLabel: 'תיאור',
      courseDescriptionPlaceholder: 'הוסיפו תיאור קצר לקורס...',
      visibilityLabel: 'הגדרת פרטיות',
      visibilityPrivate: 'פרטי',
      visibilityPublic: 'ציבורי',
      cancel: 'ביטול',
      saveCourse: 'יצירת קורס',
      deleteCourseAria: 'מחיקת הקורס {name}',
      deleteCourseModalTitle: 'מחיקת קורס',
      deleteCoursePrompt:
        'למחוק את הקורס "{name}" ואת כל החומרים, סטי השאלות והתרגולים המשויכים אליו? פעולה זו אינה ניתנת לביטול.',
      deleteCourseConfirm: 'מחיקת קורס',
      deleteCourseDeleting: 'מוחק קורס…',
      deleteCourseError: 'מחיקת הקורס נכשלה. נסו שוב.',
      deleteCourseMissingSession: 'נדרשת התחברות. התחברו מחדש.',
      brandName: 'Limdocs',
    },
    coursePage: {
      loading: 'טוען…',
      backToDashboard: 'חזרה לדאשבורד',
      accessDenied: 'אין לכם הרשאה לצפות בקורס זה.',
      courseNotFound: 'הקורס לא נמצא.',
      materialsCountStat: '{count} חומרי לימוד',
      uploadMaterial: 'העלאת חומר',
      newPracticeQuiz: 'תרגול חדש',
      quizSelectionCancel: 'ביטול בחירה',
      quizSelectDocAria: 'בחירת המסמך {name} ליצירת בוחן',
      quizSelectedCount: '{count} מסמכים נבחרו',
      quizGenerate: 'יצירת בוחן',
      quizGenerating: 'מייצר בוחן…',
      quizLoadingTitle: 'יוצרים עבורך ערכת לימוד…',
      quizGenerationSuccess: 'יצירת הבוחן החלה בהצלחה.',
      quizGenerationComplete: 'ערכת הלימוד שלכם מוכנה.',
      quizGenerationTimeout: 'יצירת הבוחן לוקחת יותר זמן מהצפוי. בדקו שוב בעוד רגע בלשונית ערכות השאלות.',
      quizGenerationError: 'יצירת הבוחן נכשלה. נסו שוב.',
      quizGenerationFailed: 'משהו השתבש ביצירת הבוחן',
      documentsRefreshFailed: 'לא הצלחנו לרענן את רשימת החומרים. ננסה שוב בקרוב.',
      tryAgain: 'נסו שוב',
      quizGenerateModalTitle: 'הגדרות יצירת בוחן',
      quizGenerateModalSubtitle: 'בחרו כמה שאלות ליצור ובאיזו שפת תוכן.',
      quizGenerateCountLabel: 'מספר שאלות',
      quizGenerateLanguageLabel: 'שפת הבוחן',
      quizGenerateCountAria: 'מספר שאלות בבוחן',
      quizGenerateLanguageAria: 'שפת תוכן הבוחן',
      quizGenerateFocusWeakLabel: 'התמקד בנושאים החלשים שלי',
      quizGenerateFocusWeakHelper:
        'אם קיימים נושאים חלשים לפי ההתקדמות שלך, המערכת תעדיף לשלב מהם יותר שאלות.',
      quizGenerateFocusWeakAria: 'התמקדות בנושאים חלשים לפי ההתקדמות שלך',
      quizLanguageOptionHe: 'עברית',
      quizLanguageOptionEn: 'אנגלית',
      quizLanguageBadgeHe: 'עברית',
      quizLanguageBadgeEn: 'אנגלית',
      questionSetMetaCount: '{count} שאלות',
      success: 'הצלחה',
      quizOverlayMessage1: 'מכינים שאלות מדויקות מהחומרים שבחרתם…',
      quizOverlayMessage2: 'מסדרים את רמת הקושי כדי שהתרגול יהיה יעיל…',
      quizOverlayMessage3: 'כמעט סיימנו. בונים עבורך ערכת לימוד חכמה…',
      materialsSectionLabel: 'חומרי הקורס',
      materialsHeading: 'חומרים',
      materialsEmpty: 'עדיין לא הועלו חומרים.',
      uploadModalTitle: 'העלאת חומר',
      uploadModalSubtitle: 'גררו קבצים לאזור למטה או לחצו לבחירה מהמחשב, ואז לחצו על העלאה.',
      uploadDropHint: 'גררו קבצים לכאן או לחצו לבחירה',
      uploadSelectedHeading: 'קבצים נבחרים',
      uploadSubmit: 'העלאה',
      uploadRemoveFileAria: 'הסרת {name}',
      uploadProgress: 'מעלה קובץ {current} מתוך {total}…',
      uploadSuccess: 'הקבצים הועלו בהצלחה.',
      uploadError: 'ההעלאה נכשלה. נסו שוב.',
      uploadFileTooLarge: 'הקובץ "{name}" גדול מדי. המקסימום הוא {max}.',
      uploadMissingCourseId: 'חסר מזהה קורס. חזרו לדאשבורד ובחרו קורס.',
      uploadMissingSession: 'נדרשת התחברות. התחברו מחדש.',
      uploadApiNotConfigured: 'ה־API לא מוגדר. הגדירו VITE_API_URL.',
      uploadUploading: 'מעלה…',
      tabMaterials: 'חומרים',
      tabQuestionSets: 'סטים של שאלות',
      tabAttempts: 'היסטוריית תרגולים',
      tabWeaknesses: 'נקודות חולשה מנותחות',
      weaknessesSectionLabel: 'ניתוח חולשות לפי נושא',
      weaknessesHeading: 'נקודות חולשה מנותחות',
      weaknessesLoading: 'טוען נתוני התקדמות…',
      weaknessesLoadError: 'לא ניתן לטעון את נתוני ההתקדמות.',
      weaknessesEmptyTitle: 'עדיין אין נתוני תרגול',
      weaknessesEmptyBody:
        'התחילו תרגול מסט שאלות כדי לראות כאן ניתוח חולשות לפי נושא ורמת קושי.',
      weaknessesEmptyCta: 'מעבר לסטי שאלות',
      weaknessDifficultyEasy: 'קל',
      weaknessDifficultyMedium: 'בינוני',
      weaknessDifficultyHard: 'קשה',
      weaknessMasteryLabel: '{percent}%',
      weaknessNotYetPracticed: 'טרם תורגל',
      weaknessStatsPracticed: '{correct}/{total}',
      weaknessListAriaLabel: 'מטריצת שליטה לפי נושא ורמת קושי',
      weaknessScoreExplainer: 'הציון מחושב לפי נכונות התשובות ורמת הקושי של השאלות.',
      weaknessStatusWeak: 'נושא חלש',
      weaknessStatusMedium: 'נושא בינוני',
      weaknessStatusStrong: 'נושא חזק',
      weaknessTopicScoreLabel: 'ציון: {score}',
      weaknessChartAriaLabel: 'גרף ציונים לפי נושא',
      weaknessChartBarAria: '{topic}: ציון {score}, {status}',
      weaknessChartLegendAria: 'מקרא צבעי ציון',
      documentTopicsAria: 'נושאי המסמך',
      attemptsSectionLabel: 'תרגולים שהוגשו',
      attemptsHeading: 'היסטוריית תרגולים',
      attemptsEmpty: 'עדיין לא הוגשו תרגולים.',
      attemptsLoading: 'טוען תרגולים…',
      attemptsLoadError: 'לא ניתן לטעון את היסטוריית התרגולים.',
      attemptsListAriaLabel: 'תרגולים שהוגשו לקורס',
      attemptScoreLabel: 'ציון: {score}%',
      attemptTimeSpentLabel: 'זמן: {time}',
      attemptQuestionSetLabel: 'סט שאלות: {name}',
      attemptTimeSecondsOnly: '{seconds} שנ׳',
      attemptTimeMinutesSeconds: '{minutes} דק׳ {seconds} שנ׳',
      backToAttemptsHistory: 'חזרה להיסטוריית תרגולים',
      viewingPastAttemptHeader: 'תרגול מ־{date} — ציון: {score}% — {setName}',
      viewPastAttemptAria: 'צפייה בתרגול מ־{date}, ציון {score} אחוז',
      deleteAttempt: 'מחיקת תרגול',
      deleteAttemptAria: 'מחיקת תרגול מ־{date}',
      deleteAttemptConfirm: 'למחוק את התרגול מ־{date} (ציון {score}%)? פעולה זו אינה ניתנת לביטול.',
      deleteAttemptSuccess: 'התרגול נמחק בהצלחה.',
      deleteAttemptError: 'מחיקת התרגול נכשלה. נסו שוב.',
      pastAttemptLoadError: 'לא ניתן לטעון את פרטי התרגול.',
      courseInnerNavAria: 'אזור ניווט בקורס',
      questionSetsSectionLabel: 'סטים של שאלות',
      questionSetsHeading: 'סטים של שאלות',
      questionSetsEmpty: 'עדיין לא נוצרו סטים של שאלות.',
      questionSetsLoadError: 'לא ניתן לטעון את סטי השאלות.',
      questionSetLoadError: 'לא ניתן לטעון את פרטי סט השאלות.',
      questionSetLoading: 'טוען שאלות…',
      questionSetUntitled: 'סט תרגול',
      questionSetDifficultySummary: '{total} שאלות: {easy} {easyLabel}, {medium} {mediumLabel}, {hard} {hardLabel}',
      backToSets: 'חזרה לבחנים',
      startAttempt: 'התחל בוחן',
      viewQuestionSet: 'צפייה בסט',
      cancelAttempt: 'ביטול',
      correctAnswer: 'תשובה נכונה',
      aiExplanation: 'הסבר AI',
      submitQuiz: 'שליחת תרגול',
      submitQuizSubmitting: 'שולח…',
      submitQuizSuccess: 'התרגול נשלח. ציון: {score}%',
      submitQuizError: 'שליחת התרגול נכשלה. נסו שוב.',
      difficultyEasy: 'קל',
      difficultyMedium: 'בינוני',
      difficultyHard: 'קשה',
      deleteSet: 'מחיקת סט',
      deleteSetAria: 'מחיקת הסט {name}',
      deleteSetConfirm: 'למחוק את הסט "{name}" ואת כל השאלות המשויכות אליו?',
      deleteSetSuccess: 'הסט נמחק בהצלחה.',
      deleteSetError: 'מחיקת הסט נכשלה. נסו שוב.',
      documentsLoading: 'טוען מסמכים…',
      documentsError: 'לא ניתן לטעון את רשימת המסמכים.',
      documentsListEmpty: 'עדיין אין מסמכים ברשימה. העלו קובץ כדי להתחיל.',
      documentsListAriaLabel: 'מסמכים שהועלו לקורס',
      statusUploaded: 'הועלה',
      statusProcessing: 'מעבד...',
      statusGenerating: 'מייצר בוחן...',
      statusReady: 'מוכן',
      statusGenerated: 'בוחן נוצר',
      statusFailed: 'שגיאה',
      deleteLabel: 'מחיקה',
      deleteDeleting: 'מוחק…',
      deleteDocumentAria: 'מחיקת המסמך {name}',
      deleteModalTitle: 'מחיקת מסמך',
      deleteConfirm: 'למחוק את המסמך "{name}"? פעולה זו אינה ניתנת לביטול.',
      deleteConfirmCta: 'מחיקה',
      deleteSuccess: 'המסמך נמחק בהצלחה.',
      deleteError: 'מחיקת המסמך נכשלה. נסו שוב.',
      visibilityHelper:
        'קורס ציבורי מופיע בלשונית גילוי הקורסים לכל המשתמשים. קורס פרטי גלוי רק לכם.',
      visibilitySaving: 'שומר את הגדרת הפרטיות…',
      visibilitySuccess: 'הגדרת הפרטיות עודכנה.',
      visibilityError: 'עדכון הגדרת הפרטיות נכשל. נסו שוב.',
      visibilityMissingSession: 'נדרשת התחברות. התחברו מחדש.',
      visibilityConfirmTitle: 'פרסום הקורס',
      visibilityConfirmPrompt:
        'קורס ציבורי יופיע בלשונית גילוי הקורסים לכל המשתמשים ב־Limdocs. להמשיך?',
      visibilityConfirmCta: 'הפוך לציבורי',
      visibilityControlAria: 'הגדרת פרטיות הקורס',
      deleteCourseLabel: 'מחיקת קורס',
      deleteCourseModalTitle: 'מחיקת קורס',
      deleteCoursePrompt:
        'למחוק את הקורס "{name}" ואת כל החומרים, סטי השאלות והתרגולים המשויכים אליו? פעולה זו אינה ניתנת לביטול.',
      deleteCourseConfirm: 'מחיקה',
      deleteCourseDeleting: 'מוחק קורס…',
      deleteCourseSuccess: 'הקורס נמחק בהצלחה.',
      deleteCourseError: 'מחיקת הקורס נכשלה. נסו שוב.',
    },
  },
  en: {
    common: {
      langHe: 'עברית',
      langEn: 'English',
      switchLanguage: 'Switch language',
    },
    login: {
      brandTitle: 'Limdocs',
      brandSubtitle: 'Personalized learning - sign in or create an account',
      footer: 'Limdocs - Adaptive learning platform',
      loginFormLabel: 'Sign in form',
      signupFormLabel: 'Create account form',
      confirmFormLabel: 'Account confirmation',
      identifierLabel: 'Username or Email',
      passwordLabel: 'Password',
      firstNameLabel: 'First Name',
      lastNameLabel: 'Last Name',
      emailLabel: 'Email',
      usernameLabel: 'Username',
      confirmCodeLabel: 'Verification Code',
      loginButton: 'Sign In',
      signupButton: 'Create Account',
      confirmButton: 'Confirm Account',
      forgotPassword: 'Forgot password',
      createNewAccount: 'Create new account',
      alreadyHaveAccount: 'Already have an account? Sign in',
      backToLogin: 'Back to sign in',
      goToConfirm: 'Go to confirmation screen',
      confirmPrompt: 'Enter the verification code sent to',
      yourEmail: 'your email',
      requiredIdentifier: 'Please enter username or email.',
      requiredPassword: 'Please enter password.',
      fillMarkedFields: 'Please fill in the fields marked in red.',
      fixMarkedFields: 'Please fix the fields marked in red.',
      signInNextStep:
        'Unable to complete sign in. An additional step may be required (for example, MFA).',
      signInFailed: 'Sign in failed. Check your details or try again later.',
      userNotFound: 'Username or email does not exist in the system',
      wrongPassword: 'The password you entered is incorrect. Please try again.',
      userNotConfirmed:
        'Your account is not confirmed yet. Check your email for a verification code.',
      signUpCodeSent:
        'A verification code was sent to your email. Enter it below to confirm your account.',
      signUpComplete: 'Sign up completed. You can now sign in.',
      signUpNotComplete: 'Sign up was not completed. Try again or contact support.',
      signUpFailed: 'Sign up failed. Check your fields and try again.',
      confirmCodeRequired: 'Please enter the verification code from your email.',
      confirmSuccess: 'Account confirmed. You can now sign in.',
      confirmFailed:
        'Verification failed. Check the code or send a new code from Cognito console.',
      requirements: {
        fullName: 'Full name is required (at least 2 words).',
        email: 'Please enter a valid email address (for example: name@example.com).',
        username: 'Username must contain at least 3 characters and no spaces.',
        password:
          'Password does not meet requirements. It must include:\n • At least 8 characters\n • One uppercase (A-Z) and one lowercase (a-z) letter\n • At least one number (0-9)\n • One special character (for example: !, @, #, $)',
      },
    },
    home: {
      loading: 'Loading…',
      navLabel: 'Main navigation',
      dashboard: 'Dashboard',
      myCourses: 'My Courses',
      documents: 'Documents',
      analytics: 'Analytics',
      settings: 'Settings',
      coursesLoading: 'Loading courses...',
      coursesError: 'Failed to load courses. Please try again.',
      coursesEmpty: 'No courses found yet.',
      untitledCourse: 'Untitled Course',
      profile: 'Profile',
      logout: 'Logout',
      greeting: 'Welcome back, {name}',
      subtext: 'Ready to continue your learning journey?',
      myCoursesSubtitle: 'Manage and resume your AI-curated study paths.',
      exploreCourses: 'Explore Courses',
      exploreCoursesSubtitle: 'Browse public courses published on Limdocs.',
      exploreCoursesLoading: 'Loading public courses…',
      exploreCoursesError: 'Failed to load public courses. Please try again.',
      exploreCoursesEmpty: 'No public courses yet.',
      exploreCourseBy: 'By {username}',
      exploreCourseOpenAria: 'Open course {name}',
      filterCourses: 'Filter',
      searchCoursesPlaceholder: 'Search courses…',
      notificationsAria: 'Notifications',
      profilePhotoAria: 'User profile',
      createCourseCardHint: 'Upload syllabus or materials to let Limdocs build your plan.',
      courseMetaDocs: '{count} Docs',
      courseMetaDocsLoading: '… Docs',
      courseMetaActivity: 'Updated {time}',
      courseMetaUnknown: '—',
      courseCardMetaLoadingAria: 'Loading course details',
      progressLabel: 'Material mastery',
      creatingCourse: 'Creating course…',
      createCourse: 'Create New Course',
      createCourseModalTitle: 'Create New Course',
      createCourseModalSubtitle: 'Enter the course details to continue.',
      courseNameLabel: 'Course Name',
      courseNamePlaceholder: 'e.g. Introduction to Computer Science',
      courseDescriptionLabel: 'Description',
      courseDescriptionPlaceholder: 'Add a short course description...',
      visibilityLabel: 'Course Visibility',
      visibilityPrivate: 'Private',
      visibilityPublic: 'Public',
      cancel: 'Cancel',
      saveCourse: 'Create Course',
      deleteCourseAria: 'Delete course {name}',
      deleteCourseModalTitle: 'Delete course',
      deleteCoursePrompt:
        'Delete "{name}" and all associated materials, question sets, and attempts? This action cannot be undone.',
      deleteCourseConfirm: 'Delete Course',
      deleteCourseDeleting: 'Deleting course…',
      deleteCourseError: 'Failed to delete course. Please try again.',
      deleteCourseMissingSession: 'Sign in required. Please sign in again.',
      brandName: 'Limdocs',
    },
    coursePage: {
      loading: 'Loading…',
      backToDashboard: 'Back to dashboard',
      accessDenied: 'You do not have access to this course.',
      courseNotFound: 'This course was not found.',
      materialsCountStat: '{count} learning materials',
      uploadMaterial: 'Upload material',
      newPracticeQuiz: 'New Practice Quiz',
      quizSelectionCancel: 'Cancel Selection',
      quizSelectDocAria: 'Select document {name} for quiz generation',
      quizSelectedCount: '{count} documents selected',
      quizGenerate: 'Generate Quiz',
      quizGenerating: 'Generating quiz…',
      quizLoadingTitle: 'Creating your study kit...',
      quizGenerationSuccess: 'Quiz generation started successfully.',
      quizGenerationComplete: 'Your study kit is ready.',
      quizGenerationTimeout: 'Quiz generation is taking longer than expected. Check the Question Sets tab again in a moment.',
      quizGenerationError: 'Quiz generation failed. Please try again.',
      quizGenerationFailed: 'Something went wrong with the quiz generation',
      documentsRefreshFailed: 'Could not refresh the materials list. We will try again shortly.',
      tryAgain: 'Try again',
      quizGenerateModalTitle: 'Quiz generation options',
      quizGenerateModalSubtitle: 'Choose how many questions to create and the quiz content language.',
      quizGenerateCountLabel: 'Number of questions',
      quizGenerateLanguageLabel: 'Quiz language',
      quizGenerateCountAria: 'Number of questions in the quiz',
      quizGenerateLanguageAria: 'Quiz content language',
      quizGenerateFocusWeakLabel: 'Focus on my weak topics',
      quizGenerateFocusWeakHelper:
        'If weak topics are available in your progress, the quiz will prioritize them.',
      quizGenerateFocusWeakAria: 'Focus quiz on weak topics from your progress',
      quizLanguageOptionHe: 'Hebrew',
      quizLanguageOptionEn: 'English',
      quizLanguageBadgeHe: 'Hebrew',
      quizLanguageBadgeEn: 'English',
      questionSetMetaCount: '{count} questions',
      success: 'Success',
      quizOverlayMessage1: 'Extracting the key ideas from your selected materials…',
      quizOverlayMessage2: 'Crafting focused questions tailored to your study flow…',
      quizOverlayMessage3: 'Almost there. Finalizing your personalized quiz set…',
      materialsSectionLabel: 'Course materials',
      materialsHeading: 'Materials',
      materialsEmpty: 'No materials uploaded yet.',
      uploadModalTitle: 'Upload material',
      uploadModalSubtitle: 'Drag files into the area below or click to browse, then click Upload.',
      uploadDropHint: 'Drag files here or click to browse',
      uploadSelectedHeading: 'Selected files',
      uploadSubmit: 'Upload',
      uploadRemoveFileAria: 'Remove {name}',
      uploadProgress: 'Uploading file {current} of {total}…',
      uploadSuccess: 'All files uploaded successfully.',
      uploadError: 'Upload failed. Please try again.',
      uploadFileTooLarge: 'The file "{name}" is too large. Maximum size is {max}.',
      uploadMissingCourseId: 'Missing course. Return to the dashboard and open a course.',
      uploadMissingSession: 'Sign in required. Please sign in again.',
      uploadApiNotConfigured: 'API is not configured. Set VITE_API_URL.',
      uploadUploading: 'Uploading…',
      tabMaterials: 'Materials',
      tabQuestionSets: 'Question Sets',
      tabAttempts: 'Attempts History',
      tabWeaknesses: 'Analyzed Weaknesses',
      weaknessesSectionLabel: 'Topic mastery analysis',
      weaknessesHeading: 'Analyzed Weaknesses',
      weaknessesLoading: 'Loading progress…',
      weaknessesLoadError: 'Could not load progress data.',
      weaknessesEmptyTitle: 'No practice data yet',
      weaknessesEmptyBody:
        'Complete a question set to see topic and difficulty mastery breakdowns here.',
      weaknessesEmptyCta: 'Go to Question Sets',
      weaknessDifficultyEasy: 'Easy',
      weaknessDifficultyMedium: 'Medium',
      weaknessDifficultyHard: 'Hard',
      weaknessMasteryLabel: '{percent}%',
      weaknessNotYetPracticed: 'Not yet practiced',
      weaknessStatsPracticed: '{correct}/{total}',
      weaknessListAriaLabel: 'Mastery matrix by topic and difficulty',
      weaknessScoreExplainer: 'Score is calculated using both correctness and question difficulty.',
      weaknessStatusWeak: 'Weak topic',
      weaknessStatusMedium: 'Medium topic',
      weaknessStatusStrong: 'Strong topic',
      weaknessTopicScoreLabel: 'Score: {score}',
      weaknessChartAriaLabel: 'Topic score chart',
      weaknessChartBarAria: '{topic}: score {score}, {status}',
      weaknessChartLegendAria: 'Score color legend',
      documentTopicsAria: 'Document topics',
      attemptsSectionLabel: 'Quiz attempts',
      attemptsHeading: 'Attempts History',
      attemptsEmpty: 'No attempts yet.',
      attemptsLoading: 'Loading attempts…',
      attemptsLoadError: 'Could not load attempts.',
      attemptsListAriaLabel: 'Submitted quiz attempts',
      attemptScoreLabel: 'Score: {score}%',
      attemptTimeSpentLabel: 'Time spent: {time}',
      attemptQuestionSetLabel: 'Question set: {name}',
      attemptTimeSecondsOnly: '{seconds}s',
      attemptTimeMinutesSeconds: '{minutes}m {seconds}s',
      backToAttemptsHistory: 'Back to Attempts History',
      viewingPastAttemptHeader: 'Attempt from {date} — Score: {score}% — {setName}',
      viewPastAttemptAria: 'View attempt from {date}, score {score} percent',
      deleteAttempt: 'Delete Attempt',
      deleteAttemptAria: 'Delete attempt from {date}',
      deleteAttemptConfirm: 'Delete the attempt from {date} (score {score}%)? This cannot be undone.',
      deleteAttemptSuccess: 'Attempt deleted successfully.',
      deleteAttemptError: 'Failed to delete attempt. Please try again.',
      pastAttemptLoadError: 'Could not load attempt details.',
      courseInnerNavAria: 'Course section navigation',
      questionSetsSectionLabel: 'Question sets',
      questionSetsHeading: 'Question Sets',
      questionSetsEmpty: 'No question sets generated yet.',
      questionSetsLoadError: 'Could not load question sets.',
      questionSetLoadError: 'Could not load question set details.',
      questionSetLoading: 'Loading questions…',
      questionSetUntitled: 'Practice Set',
      questionSetDifficultySummary: '{total} Questions: {easy} {easyLabel}, {medium} {mediumLabel}, {hard} {hardLabel}',
      backToSets: 'Back to Question Sets',
      startAttempt: 'Start Attempt',
      viewQuestionSet: 'View Question Set',
      cancelAttempt: 'Cancel',
      correctAnswer: 'Correct answer',
      aiExplanation: 'AI explanation',
      submitQuiz: 'Submit Quiz',
      submitQuizSubmitting: 'Submitting…',
      submitQuizSuccess: 'Quiz submitted. Score: {score}%',
      submitQuizError: 'Failed to submit quiz. Please try again.',
      difficultyEasy: 'Easy',
      difficultyMedium: 'Medium',
      difficultyHard: 'Hard',
      deleteSet: 'Delete Set',
      deleteSetAria: 'Delete set {name}',
      deleteSetConfirm: 'Delete "{name}" and all associated questions?',
      deleteSetSuccess: 'Set deleted successfully.',
      deleteSetError: 'Failed to delete set. Please try again.',
      documentsLoading: 'Loading documents…',
      documentsError: 'Could not load documents.',
      documentsListEmpty: 'No documents in the list yet. Upload a file to get started.',
      documentsListAriaLabel: 'Documents uploaded to this course',
      statusUploaded: 'Uploaded',
      statusProcessing: 'Processing...',
      statusGenerating: 'Generating quiz...',
      statusReady: 'Ready',
      statusGenerated: 'Generated',
      statusFailed: 'Error',
      deleteLabel: 'Delete',
      deleteDeleting: 'Deleting…',
      deleteDocumentAria: 'Delete document {name}',
      deleteModalTitle: 'Delete document',
      deleteConfirm: 'Delete "{name}"? This action cannot be undone.',
      deleteConfirmCta: 'Delete',
      deleteSuccess: 'Document deleted successfully.',
      deleteError: 'Failed to delete document. Please try again.',
      visibilityHelper:
        'A public course appears on Explore Courses for everyone. A private course is visible only to you.',
      visibilitySaving: 'Saving visibility…',
      visibilitySuccess: 'Course visibility updated.',
      visibilityError: 'Could not update visibility. Please try again.',
      visibilityMissingSession: 'Sign in required. Please sign in again.',
      visibilityConfirmTitle: 'Make course public',
      visibilityConfirmPrompt:
        'A public course will appear on Explore Courses for every Limdocs user. Continue?',
      visibilityConfirmCta: 'Make public',
      visibilityControlAria: 'Course visibility',
      deleteCourseLabel: 'Delete Course',
      deleteCourseModalTitle: 'Delete course',
      deleteCoursePrompt:
        'Delete "{name}" and all associated materials, question sets, and attempts? This action cannot be undone.',
      deleteCourseConfirm: 'Delete',
      deleteCourseDeleting: 'Deleting course…',
      deleteCourseSuccess: 'Course deleted successfully.',
      deleteCourseError: 'Failed to delete course. Please try again.',
    },
  },
}
