export const languageContent = {
  he: {
    common: {
      langHe: 'עברית',
      langEn: 'English',
      switchLanguage: 'החלפת שפה',
    },
    login: {
      brandTitle: 'Limdocs',
      brandSubtitle: 'Limdocs - למידה מותאמת אישית — התחברו או צרו חשבון',
      footer: 'Limdocs — פלטפורמת למידה אדפטיבית',
      loginFormLabel: 'טופס התחברות',
      signupFormLabel: 'טופס יצירת חשבון',
      confirmFormLabel: 'אישור חשבון',
      identifierLabel: 'שם משתמש או אימייל',
      passwordLabel: 'סיסמה',
      firstNameLabel: 'שם פרטי',
      lastNameLabel: 'שם משפחה',
      emailLabel: 'אימייל',
      usernameLabel: 'שם משתמש',
      confirmCodeLabel: 'קוד אימות',
      loginButton: 'התחברות',
      signupButton: 'צור חשבון',
      confirmButton: 'אשר חשבון',
      forgotPassword: 'שכחתי סיסמה',
      createNewAccount: 'צור חשבון חדש',
      alreadyHaveAccount: 'כבר יש לך חשבון? התחבר',
      backToLogin: 'חזרה להתחברות',
      goToConfirm: 'מעבר למסך אישור חשבון',
      confirmPrompt: 'הזינו את קוד האימות שנשלח ל־',
      yourEmail: 'האימייל שלך',
      requiredIdentifier: 'יש להזין שם משתמש או אימייל.',
      requiredPassword: 'יש להזין סיסמה.',
      fillMarkedFields: 'יש למלא את השדות המסומנים באדום.',
      fixMarkedFields: 'יש לתקן את השדות המסומנים באדום.',
      signInNextStep:
        'לא ניתן להשלים כניסה. ייתכן שנדרש שלב נוסף (למשל אימות דו-שלבי).',
      signInFailed: 'התחברות נכשלה. בדקו את הפרטים או נסו שוב מאוחר יותר.',
      userNotFound: 'שם המשתמש או האימייל אינם קיימים במערכת',
      wrongPassword: 'הסיסמה שהזנת אינה נכונה. נסה שנית.',
      userNotConfirmed: 'חשבונך טרם אומת. בדוק את המייל לקוד אישור.',
      signUpCodeSent: 'נשלח קוד אימות לאימייל. הזינו אותו למטה לאישור החשבון.',
      signUpComplete: 'ההרשמה הושלמה. כעת ניתן להתחבר.',
      signUpNotComplete: 'ההרשמה לא הושלמה. נסו שוב או פנו לתמיכה.',
      signUpFailed: 'הרשמה נכשלה. בדקו את השדות ונסו שוב.',
      confirmCodeRequired: 'נא להזין את קוד האימות מהאימייל.',
      confirmSuccess: 'החשבון אושר. ניתן להתחבר.',
      confirmFailed: 'אימות נכשל. בדקו את הקוד או שלחו קוד חדש מקונסולת Cognito.',
      requirements: {
        fullName: 'חובה להזין שם מלא (לפחות 2 מילים).',
        email: 'יש להזין כתובת אימייל תקינה (למשל: name@example.com).',
        username: 'שם משתמש חייב להכיל לפחות 3 תווים, ללא רווחים.',
        password:
          'הסיסמה אינה עומדת בדרישות. עליה להכיל:\n • לפחות 8 תווים\n • אות גדולה (A-Z) ואות קטנה (a-z)\n • לפחות מספר אחד (0-9)\n • תו מיוחד (למשל: !, @, #, $)',
      },
    },
    home: {
      loading: 'טוען…',
      navLabel: 'ניווט ראשי',
      dashboard: 'דאשבורד',
      myCourses: 'הקורסים שלי',
      coursesLoading: 'טוען קורסים...',
      coursesError: 'טעינת הקורסים נכשלה. נסו שוב.',
      coursesEmpty: 'עדיין לא נרשמתם לקורסים.',
      untitledCourse: 'קורס ללא שם',
      profile: 'פרופיל',
      logout: 'התנתקות',
      greeting: 'שלום, {name}',
      subtext: 'מוכנים להתחיל? כאן תוכלו להתחיל לבנות סביבת למידה חדשה.',
      createCourse: 'ליצירת קורס חדש',
      createCourseModalTitle: 'יצירת קורס חדש',
      createCourseModalSubtitle: 'הזינו את פרטי הקורס כדי להמשיך.',
      courseNameLabel: 'שם הקורס',
      courseNamePlaceholder: 'למשל: מבוא למדעי המחשב',
      courseDescriptionLabel: 'תיאור',
      courseDescriptionPlaceholder: 'הוסיפו תיאור קצר לקורס...',
      visibilityLabel: 'הגדרת פרטיות',
      visibilityPrivate: 'פרטי',
      visibilityPublic: 'ציבורי',
      cancel: 'ביטול',
      saveCourse: 'יצירת קורס',
      brandName: 'Limdocs',
    },
    coursePage: {
      loading: 'טוען…',
      backToDashboard: 'חזרה לדאשבורד',
      materialsCountStat: '{count} חומרי לימוד',
      uploadMaterial: 'העלאת חומר',
      materialsSectionLabel: 'חומרי הקורס',
      materialsHeading: 'חומרים',
      materialsEmpty: 'עדיין לא הועלו חומרים.',
    },
  },
  en: {
    common: {
      langHe: 'עברית',
      langEn: 'English',
      switchLanguage: 'Switch language',
    },
    login: {
      brandTitle: 'Limdocs',
      brandSubtitle: 'Personalized learning - sign in or create an account',
      footer: 'Limdocs - Adaptive learning platform',
      loginFormLabel: 'Sign in form',
      signupFormLabel: 'Create account form',
      confirmFormLabel: 'Account confirmation',
      identifierLabel: 'Username or Email',
      passwordLabel: 'Password',
      firstNameLabel: 'First Name',
      lastNameLabel: 'Last Name',
      emailLabel: 'Email',
      usernameLabel: 'Username',
      confirmCodeLabel: 'Verification Code',
      loginButton: 'Sign In',
      signupButton: 'Create Account',
      confirmButton: 'Confirm Account',
      forgotPassword: 'Forgot password',
      createNewAccount: 'Create new account',
      alreadyHaveAccount: 'Already have an account? Sign in',
      backToLogin: 'Back to sign in',
      goToConfirm: 'Go to confirmation screen',
      confirmPrompt: 'Enter the verification code sent to',
      yourEmail: 'your email',
      requiredIdentifier: 'Please enter username or email.',
      requiredPassword: 'Please enter password.',
      fillMarkedFields: 'Please fill in the fields marked in red.',
      fixMarkedFields: 'Please fix the fields marked in red.',
      signInNextStep:
        'Unable to complete sign in. An additional step may be required (for example, MFA).',
      signInFailed: 'Sign in failed. Check your details or try again later.',
      userNotFound: 'Username or email does not exist in the system',
      wrongPassword: 'The password you entered is incorrect. Please try again.',
      userNotConfirmed:
        'Your account is not confirmed yet. Check your email for a verification code.',
      signUpCodeSent:
        'A verification code was sent to your email. Enter it below to confirm your account.',
      signUpComplete: 'Sign up completed. You can now sign in.',
      signUpNotComplete: 'Sign up was not completed. Try again or contact support.',
      signUpFailed: 'Sign up failed. Check your fields and try again.',
      confirmCodeRequired: 'Please enter the verification code from your email.',
      confirmSuccess: 'Account confirmed. You can now sign in.',
      confirmFailed:
        'Verification failed. Check the code or send a new code from Cognito console.',
      requirements: {
        fullName: 'Full name is required (at least 2 words).',
        email: 'Please enter a valid email address (for example: name@example.com).',
        username: 'Username must contain at least 3 characters and no spaces.',
        password:
          'Password does not meet requirements. It must include:\n • At least 8 characters\n • One uppercase (A-Z) and one lowercase (a-z) letter\n • At least one number (0-9)\n • One special character (for example: !, @, #, $)',
      },
    },
    home: {
      loading: 'Loading…',
      navLabel: 'Main navigation',
      dashboard: 'Dashboard',
      myCourses: 'My Courses',
      coursesLoading: 'Loading courses...',
      coursesError: 'Failed to load courses. Please try again.',
      coursesEmpty: 'No courses found yet.',
      untitledCourse: 'Untitled Course',
      profile: 'Profile',
      logout: 'Logout',
      greeting: 'Hello, {name}',
      subtext: 'Ready to start? Create your next learning space here.',
      createCourse: 'Create New Course',
      createCourseModalTitle: 'Create New Course',
      createCourseModalSubtitle: 'Enter the course details to continue.',
      courseNameLabel: 'Course Name',
      courseNamePlaceholder: 'e.g. Introduction to Computer Science',
      courseDescriptionLabel: 'Description',
      courseDescriptionPlaceholder: 'Add a short course description...',
      visibilityLabel: 'Course Visibility',
      visibilityPrivate: 'Private',
      visibilityPublic: 'Public',
      cancel: 'Cancel',
      saveCourse: 'Create Course',
      brandName: 'Limdocs',
    },
    coursePage: {
      loading: 'Loading…',
      backToDashboard: 'Back to dashboard',
      materialsCountStat: '{count} learning materials',
      uploadMaterial: 'Upload material',
      materialsSectionLabel: 'Course materials',
      materialsHeading: 'Materials',
      materialsEmpty: 'No materials uploaded yet.',
    },
  },
}
